[build]
  command = "npm run build"
  publish = "public"
  
[build.environment]
  HUGO_VERSION = "0.121.0"
  NODE_VERSION = "18"
  HUGO_ENV = "production"

[context.production]
  command = "npm run build:datocms && hugo --gc --minify --config config.prod.toml"
